name: 天天领白条券

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  watch:
    types: started
  repository_dispatch:
    types: jd_scripts
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: DoveBoy/jd_scripts-gcdd1993
          ref: 'master'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          npm install
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: 阻塞运行
        run: |
          curl https://raw.githubusercontent.com/x1iu/jd_scripts/master/wait24.py -o wait.py
          python3 wait.py
      - name: '运行 【天天领白条券】'
        run: |
          node jd_baitiao.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}