name: 京年团圆1-20
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,3,7,11 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: x1iu/bbaase
          ref: 'main'
          token: ${{ secrets.PAT }}  