name: jd_joy_reward

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23,7,15 * * *'
  watch:
    types: started
  repository_dispatch:
    types: joy_reward
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: x1iu/bbaase
          ref: 'main'
          token: ${{ secrets.PAT }}        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          npm install
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: 阻塞运行
        run: |
          curl https://raw.githubusercontent.com/x1iu/jd_scripts/master/accwait.py -o wait.py
          python3 wait.py 1 0.1
      - name: '运行 【宠汪汪积分兑换京豆】'
        run: |
          for ((a=1; a <= 25; a++))
          do
              node jd_joy_reward.js &
              sleep 0.1
          done
          sleep 10
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          JD_JOY_REWARD_NOTIFY: ${{ secrets.JD_JOY_REWARD_NOTIFY }}
          JD_JOY_REWARD_NAME: ${{ secrets.JD_JOY_REWARD_NAME }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
      - name: '运行 【兑换20京豆】'
        run: |
          hours=`date +%H`
          if [ $hours -eq 8 ]
          then
          node jd_joy_reward.js
          else
          echo "none"
          fi
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          JD_JOY_REWARD_NOTIFY: ${{ secrets.JD_JOY_REWARD_NOTIFY }}
          JD_JOY_REWARD_NAME: "20"
